Set oWS = WScript.CreateObject("WScript.Shell")
Set oWN = WScript.CreateObject("WScript.Network")
Set url=CreateObject("WScript.Shell")
set x=createobject("wscript.shell")
Set oFS = WScript.CreateObject("Scripting.FileSystemObject")

x.run "notepad.exe"
wscript.sleep 1000
x.sendkeys"Set wshShell =wscript.CreateObject(WScript.Shell)"
x.sendkeys"""{)}"""
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"""{(}"""
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{BS}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{BS}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{ENTER}"
x.sendkeys"set x=createobjectwscript.shell"
x.sendkeys"""{)}"""
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"""{(}"""
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{BS}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{LEFT}"
x.sendkeys"{BS}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{RIGHT}"
x.sendkeys"{ENTER}"
x.sendkeys"{ENTER}"
x.sendkeys"'............................................................................................................................................................................."
x.sendkeys"{ENTER}"
x.sendkeys"'Important code"
x.sendkeys"{ENTER}"
x.sendkeys"'dont forget this"
x.sendkeys"{ENTER}"
x.sendkeys"'very useful"
x.sendkeys"{ENTER}"
x.sendkeys"'wscript.sleep 1000...........................waits specific amount of time in miliseconds"
x.sendkeys"{ENTER}"
x.sendkeys"'x.sendkeys.......................................Sends keys like words or keys"
x.sendkeys"{ENTER}"
x.sendkeys"'x.run.................................................Runs an application"
x.sendkeys"{ENTER}"
x.sendkeys"'This setup maker was made by Hannah i hope u like it."
x.sendkeys"{ENTER}"
x.sendkeys"'for more keystrokes go to:https://social.technet.microsoft.com/wiki/contents/articles/5169.vbscript-sendkeys-method.aspx"
x.sendkeys"{ENTER}"
x.sendkeys"'............................................................................................................................................................................."
x.sendkeys"{ENTER}"
x.sendkeys"{ENTER}"
WshShell.SendKeys "^{s}"
wscript.sleep 1000
x.sendkeys "Setupmakermade.vbs"
wshshell.sendkeys "{ENTER}"




